assets/scss/_variables.scss, assets/scss/app.scss, assets/scss/components/_card.scss, components/AppHero/AppHeroOuter.vue, components/Poems/PoemCard.vue, layouts/default.vue, pages/index.vue, pages/poems/_id.vue, store/index.js
This isn't done, but I have to start work on some other stuff and it would be good to get in some of this change now before it gets stale.
=> #94: Stub out some styles, start differentiating pages

assets/scss/imports.js, nuxt.config.js, package.json, yarn.lock
It seems so insignificant to look at but I was banging my head against the wall. A lot. 
This is the article that finally kicked it over the edge for me https://itnext.io/sharing-sass-resources-with-sass-resources-loader-and-webpack-ca470cd11746
=> All the bootstraps

.gitignore, .lando.yml, .travis.yml, components/AppPromoSpace.vue, test/home_test.js
This simplifies our appserver and offloads the testing to codeceptions own image.
=> Simpler test

components/FeatureCard.vue, pages/styleguide.vue
=> Individual feature card

assets/scss/app.scss, assets/scss/components/atoms/_breakpoint-visualizer.scss, assets/scss/components/organisms/_card-deck--featurecard.scss, assets/scss/components/organisms/_card-deck--poet.scss, components/CardDeck.vue, components/FeatureCard.vue, pages/styleguide.vue
=> Feature deck

assets/scss/app.scss, assets/scss/components/molecules/_pager.scss, assets/scss/components/organisms/_tabular-list.scss, pages/_vertical/poem-a-day.vue, pages/_vertical/poet/index.vue
=> Previous poems list

components/CardDeck.vue, components/TeachingCard.vue, components/TeachingIntro.vue, pages/styleguide.vue
=> Teacher intro and Teaching Card

pages/_slug.vue, pages/_vertical/_slug.vue
We can now load these pages dynamically, the page needs a custom alias if we want to use the /privacy link
=> Issue #361: Load verticaless pages

plugins/poets-api/index.js, plugins/poets-api/lib/sections.js
@dustinleblanc was able to win this with WAY less effort than i thought was required.
=> #379: vuex store bleed

components/AppNewsletterSupportFollow/AppNewsletter.vue, components/Login.vue, components/PasswordReset.vue, components/PoemActions.vue, components/Register.vue, components/SignupBlock.vue, pages/login.vue, pages/register.vue, pages/reset.vue
-  [ ] The old site sets the default/placeholder "newsletter signup" email to the logged in users email if applicable. So if you are logged in you should see your email in the "newsletter signup" form. If you are not logged in you should see "john@example.com" which is the current placeholder
=> 506 anthologies logged out

pages/poet/_title.vue
@pirog @dbungard there is no ticket for this, but noticed whilst working on #525 so put up a quick pr.
QA:
=> If poet has no data for dob do not show dashes.

pages/search/index.vue, plugins/search-helpers.js
The backend PR https://github.com/thinktandem/poets-api/pull/604 needs to merged along side of this as the search view has changed,
=> #588 Redo search view calls

pages/libraries.vue
@pirog there is no issue for this, but found it in my travels.
=> Fix broken texts link from /libraries page.

pages/poets/index.vue
Also populate URL with search params
=> Issue #697: Show the selected movement

pages/403.vue, pages/404.vue, pages/american-poets-magazine/index.vue, pages/index.vue, pages/poets/index.vue, plugins/axios.js, plugins/error-handler.js, plugins/poets-api/index.js, plugins/poets-apiv2/index.js, plugins/poets-apiv2/lib/magazines.js, plugins/poets-apiv2/lib/poets.js, store/index.js
=> #763: NETWORK ERROR DEBUG 1

pages/academy-american-poets/index.vue, pages/libraries.vue
@dustinleblanc et al dont QA or merge this in yet, trying to remove `await` usage on critical pages to enhance performance and unify patterns... but wanted to have an env spun up to test
=> #PIRO426-2: Stop waiting on AAP

.platform/routes.yaml, components/AppNavigation.vue
=> #725: Disable frontend cache to assess login weirdness

components/AppFeature.vue, components/FeatureStack.vue
Also add some padding on desktop feature stacks
=> Issue thinktandem/poets-api#769: Fix squashed mobile feature images

components/AnthologyActions.vue, pages/anthology/_title.vue
This also adds in some functionality we didn't document from the old
site
=> Issue thinktandem/poets-api#710: Paginate Anthologies

pages/poem/_title.vue
=> thinktandem/poets-api#SLACK: Fix titles on poem iframe embeds.

pages/poems/_author.vue
=> thinktandem/poets-api#875: Adding metatags for /poems/{author} pages.

assets/scss/components/molecules/_promo.scss, components/PromoSpace.vue
=> thinktandem/poets-api#880: Use Billboard 970x250 ads on screen > 1024.

middleware/redirects.js
=> Hotfix: Fix text page redirects

redirects.json
=> #889 Few more high value redirects

redirects.json
=> Add in odd redirect for Langsotn Hughes

middleware/redirects.js
=> Fix unresolved var

components/AppFooter/AppFooterPrimary.vue
=> Hotfix: Cleanup external footer link

middleware/redirects.js, pages/node/_id.vue, pages/poems/_author.vue, plugins/axios.js
=> SLACK: Set known redirects to 301 status code.

pages/poems/_author.vue
=> thinktandem/poets-api#900 Override poems by title

components/EssayCard.vue, components/Poems/PoemCard.vue, pages/poem/_title.vue
=> #914 Change articles to creative work schema

pages/poems/_author.vue, pages/print/poem/_uuid.vue
=> thinktandem/poets-api#887 Remove print page from index and add a title

pages/_vertical/winner/_program/_parent/_title.vue
=> thinktandem/poets-api#887 Fix winner metatags

pages/poems/_author.vue
=> Remove quotes around poet name

pages/_vertical/programs/index.vue, pages/institution/_title.vue, pages/lesson-plan/_title.vue, pages/listing/_title.vue, pages/poems/_author.vue, pages/teach-poem/_title.vue, pages/texts/_author.vue
=> thinktandem/poets-api#917: Adding metatag data to /lesson-plans/_title.

nuxt.config.js
=> #948: Adding getsitecontrol script to all pages.

components/AppHero/AppHeroOuter.vue, components/AppNavigation.vue, layouts/sparse.vue, pages/donate/_title.vue
=> Issue thinktandem/poets-api#939: Stripped down donate pages.

components/AppHero/AppHeroOuter.vue
=> Swap to AAP logo on donation pages

pages/poems/index.vue
=> Safer access to copyright date

pages/poems/index.vue
=> Issue thinktandem/poets-api#950: Properly pull Poet name

package.json, yarn.lock
=> Update serialize-javascript (security)

package.json, yarn.lock
=> Upgrade webpack-bundle-analyzer (security)

pages/index.vue, pages/national-poetry-month/index.vue, pages/poem-a-day.vue, plugins/metatags.js
=> Issue #961: Fix Powerad script inclusion
